#this program says hello and asks for my name.
print('hello')
print('whats is your name')
print('enter your name')
myname=input()
print('is id good to meet you'+myname)
print('the length of your name is ')
print(len(myname))
print('what is your age')
myage=input()
print('you will be '+str(int(myage)+1)+'in this year')
